runtime: nodejs10
instance_class: F4
default_expiration: "30d"
automatic_scaling:
  max_instances: 19
  min_instances: 0

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always
    http_headers:
      Vary: Accept-Encoding

  - url: /(.*\.(gif|png|jpg|ico|txt|svg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt|svg)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
